#!/usr/bin/env bash

if which ansible >/dev/null; then
    echo "Ansible already installed"
    exit 0
fi

apt-get update \
&& apt-get install -y software-properties-common \
&& apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 6125E2A8C77F2818FB7BD15B93C4A3FD7BB9C367 \
&& echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu xenial main" > /etc/apt/sources.list.d/ansible.list \
&& echo "deb-src http://ppa.launchpad.net/ansible/ansible/ubuntu xenial main" >> /etc/apt/sources.list.d/ansible.list \
&& apt-get update \
&& apt-get install -y -f ansible
